#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint 
npm run format
npm run test
cargo fmt --all --manifest-path="src-tauri/Cargo.toml"
cargo test --manifest-path="src-tauri/Cargo.toml"
git add .
